services:
  # db:
  #   image: postgres:15
  #   container_name: postgres_db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - default

  app:
    platform: "linux/amd64"
    container_name: app
    build: .
    image: app:latest
    working_dir: /app
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - ./crawl-results:/app/crawl-results
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
    env_file:
      - .env
    networks:
      - default
    command: pnpm dev

  crawler:
    platform: "linux/amd64"
    container_name: crawler
    build: .
    image: app:latest
    working_dir: /app
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - ./crawl-results:/app/crawl-results
    environment:
      - NODE_ENV=development
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
    env_file:
      - .env
    networks:
      - default
    command: pnpm start

volumes:
  postgres_data:

networks:
  default:
    driver: bridge